### ISSUE TITLE
Fails to build with python-3.9

### ISSUE THREAD

**Issue by ondrejj** [nandoflorestan/nine#3]
```


python-nine fails to build with Python 3.9.0a2.

======================================================================
ERROR: test_import (nine.test_nine.TestNine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/nine-0.3.4/nine/test_nine.py", line 21, in test_import
    assert nimport(key)
  File "/builddir/build/BUILD/nine-0.3.4/nine/__init__.py", line 208, in nimport
    module = import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1016, in _gcd_import
  File "<frozen importlib._bootstrap>", line 993, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_dummy_thread'
----------------------------------------------------------------------
```
More info here:
https://bugzilla.redhat.com/show_bug.cgi?id=1792968

**Comment by nandoflorestan** [comment]
Thank you for creating this issue.

travis-ci now says that nine builds fine on python 3.9, since
https://github.com/nandoflorestan/nine/commit/8df641cfb245e33054d4267c97671471a55f68dc

I am making a release now.
